evolving script to avoid build loop

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,12 +2,35 @@ language: node_js
 node_js:
   - "10"
 
-#after_success:
-deploy:
-  provider: pages
-  skip-cleanup: true
-  github-token: $GITHUB_TOKEN
-  keep-history: true
-  target-branch: master
-  on:
-    branch: master
+#unhappyly the worst happened - an infinite build-push-trigger loop
+#deploy:
+#  provider: pages
+#  skip-cleanup: true
+#  github-token: $GITHUB_TOKEN
+#  keep-history: true
+#  target-branch: master
+#  on:
+#    branch: master
+
+after_success: |
+  if [ -n "$GITHUB_TOKEN" ]; then
+    #configure
+    git config user.name "travis@travis-ci.org"
+    git config user.email "Travis CI"
+    #
+    git checkout -q master
+    #list of staged files
+    git add -f apps/idate/dist/*
+    #
+    git commit -m "Travis update: `date "+%b %Y"` (Build $TRAVIS_BUILD_NUMBER)" -m "[skip ci]"
+
+    # push only if "git commit" succeeded
+    if [ $? -eq 0 ]; then
+      echo "pushing...."
+      #git remote rm origin
+      git remote add origin https://henriquericcio:$GITHUB_TOKEN@github.com/codingzenorg/site.git > /dev/null 2>&1
+      git push origin master --quiet
+    else
+      echo "No changes. Nothing to do"
+    fi
+  fi
